enum packet
    {
    null,
    add_socket,
    remove_socket,
    update_entities,
    inform_sss,
    ping,//5
    ping_report,
    chat,
    entity_create,
    entity_destroy,
    update_sockets,//10
    entity_command,
    fire_weapon,
    issue_command,
    entity_send,
    rubberband_entity,//15
    entity_set_pilot,
    grid_set,
    entity_dock,
    inventory,
    set_ownership,//20
    login,
    types,
    }
