///Event_Keyboard()

keyboard_pressed_f1()
keyboard_pressed_f2()
keyboard_pressed_f3()
keyboard_pressed_f4()
keyboard_pressed_f5()

keyboard_pressed_escape()
keyboard_pressed_enter()
keyboard_pressed_space()
keyboard_pressed_control()

keyboard_pressed_c()
keyboard_pressed_x()
keyboard_pressed_v()

keyboard_pressed_e()
keyboard_pressed_s()
keyboard_pressed_d()
keyboard_pressed_f()
keyboard_pressed_i()
keyboard_pressed_j()
keyboard_pressed_k()
keyboard_pressed_l()

keyboard_released_space()

keyboard_released_e()
keyboard_released_s()
keyboard_released_d()
keyboard_released_f()
keyboard_released_i()
keyboard_released_j()
keyboard_released_k()
keyboard_released_l()
